info:
  app:
    name: 'PTN :: Article Management Service'
    description: The PTN product.
    version: 1.0.0

server:
  port: 8081
  servlet:
    session:
      timeout: 1m
  #server.servlet.context-path=/ptn/finance-management/api


management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
  endpoints.web.base-path: /actuator

spring:
  jpa.hibernate:
    ddl-auto: validate
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/NoticeManagementService
    username: ptn_admin
    password: ptn_admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.show-sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-version: 00000000.000000
    table: SchemaHistory
    out-of-order: true
    #multipart config
  http.multipart:
    file-size-threshold: 2MB
    max-file-size: 10MB
    max-request-size: 10MB
jjwt:
  secret: abc
  expiration.ms: 3600000
  cookie-name: ptn-notices
  #spring.thymeleaf.cache=false